# Generated by Django 2.2.3 on 2019-07-20 11:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20190720_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='add_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
