# Generated by Django 2.2.3 on 2019-07-20 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='文章标题', max_length=50)),
                ('date', models.DateTimeField()),
                ('image', models.ImageField(default='default.png', upload_to='image/')),
                ('text', models.TextField(default='正文')),
            ],
        ),
    ]
